version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: louis-portfolio

  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    container_name: louis-portfolio-dev
    profiles:
      - dev